limit_req_zone $binary_remote_addr zone=health_limit:10m rate=1r/s;

upstream backend_app {
  zone backend_app 64k;
  server app1:3000;
  server app2:3000;
  keepalive 2;
}

server {
  listen 80;

  location / {
    proxy_pass         http://backend_app;
    proxy_http_version 1.1;
    proxy_set_header   Connection "";
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
  }

  location /health {
    limit_req          zone=health_limit burst=3 nodelay;
    limit_req_status   429;
    proxy_pass         http://backend_app;
    proxy_http_version 1.1;
    proxy_set_header   Connection "";
  }
}